/** Names for document categories and owners, shown across the platform. */

export const CATEGORY_LABELS = {
  passport: 'Passport',
  loa: 'Letter of Acceptance',
  pal: 'Provincial Attestation Letter',
  'proof-of-funds': 'My bank statement',
  'source-of-funds': 'Source of my money',
  'affidavit-support': 'Affidavit of support',
  'title-deeds': 'My title deeds',
  'supporter-bank': "Supporter's bank statements",
  'supporter-income': "Supporter's pay slips / employment",
  'supporter-deeds': "Supporter's title deeds",
  'supporter-id': "Supporter's birth certificate / ID",
  gic: 'GIC certificate',
  deposit: 'Tuition deposit / receipt',
  photo: 'Photo',
  transcripts: 'Degree & transcripts',
  certificates: 'Certificates',
  cv: 'CV / résumé',
  'national-id': 'Birth certificate / national ID',
  language: 'Language test result',
  sop: 'Statement of Purpose',
  'employment-letter': 'Employment letter',
  'job-offer': 'Job offer letter',
  lmia: 'LMIA / offer of employment (IMM 5802)',
  'employment-contract': 'Employment contract',
  'leave-of-absence': 'Leave of absence letter',
  internship: 'Internship certificate',
  'ties-docs': 'Ties to home country docs',
  'police-clearance': 'Police clearance',
  military: 'Military service card',
  flight: 'Flight reservation',
  accommodation: 'Accommodation',
  medical: 'Medical exam',
  'family-info': 'Family information',
  'marriage-cert': 'Marriage certificate',
  'spouse-status': "Spouse's permit in Canada",
  'inviter-docs': "Spouse's / inviter's documents (employment, income, lease)",
  'host-docs': "Host's status & documents",
  'invitation-letter': 'Invitation letter',
  'status-in-canada': 'My current permit in Canada',
  'last-entry': 'Proof of last entry to Canada',
  'completion-letter': 'Completion of studies letter',
  'consent-letter': "Parents' consent letter",
  'custody-doc': 'Custody / guardianship document',
  'refusal-letter': 'Previous refusal / GCMS notes / old application',
  insurance: 'Social insurance records',
  'travel-history': 'Previous visas & travel history',
  'enrolment-letter': 'Enrolment letter / school enrolment certificate',
  'residence-abroad': 'Residence in another country',
  'relationship-proof': 'Proof of relationship to the inviter',
  'medical-insurance': 'Medical insurance (Super Visa)',
  scholarship: 'Funding / scholarship letter',
  'co-op-letter': 'Co-op letter',
  'research-proposal': 'Research proposal',
  'business-docs': 'Business documents (registration, licences)',
  'business-financials': 'Business financial statements & tax returns',
  'business-contracts': 'Business contracts & partnership agreements',
  'business-employees': 'Business employees & employment contracts',
  'business-premises': 'Business premises (deeds / leases)',
  'business-plan': 'Canadian business plan & job offer',
  questionnaire: 'Questionnaire (111 SOP / POT) — used to write the letter',
  'rep-form': 'IRCC form (IMM 5476, 5713…)',
  internal: 'Internal / intake form (never compiled)',
  other: 'Other',
};

export const OWNER_LABELS = { spouse: 'the spouse', child: 'a child', parent: 'a parent', host: 'the host', sponsor: 'a sponsor', other: 'someone else' };
